In [1]:
pip install tensorflow

  Using cached tensorflow-2.5.0-cp38-cp38-win_amd64.whl (422.6 MB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Note: you may need to restart the kernel to use updated packages.
  Using cached grpcio-1.34.1-cp38-cp38-win_amd64.whl (2.9 MB)
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached h5py-3.1.0-cp38-cp38-win_amd64.whl (2.7 MB)
  Using cached tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
  Using cached google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
 

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [3]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, trains_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [4]:
train_images.shape

(60000, 28, 28)

In [10]:
len(trains_labels)

60000

In [11]:
np.unique(trains_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [8]:
test_images.shape

(10000, 28, 28)

In [9]:
len(test_labels)

10000

In [12]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [13]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [15]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [17]:
model.fit(train_images, trains_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 690us/step - loss: 0.4994 - accuracy: 0.8245
Epoch 2/5
1875/1875 [==============================] - 1s 664us/step - loss: 0.3765 - accuracy: 0.8630
Epoch 3/5
1875/1875 [==============================] - 1s 638us/step - loss: 0.3358 - accuracy: 0.8779
Epoch 4/5
1875/1875 [==============================] - 1s 639us/step - loss: 0.3121 - accuracy: 0.8857
Epoch 5/5
1875/1875 [==============================] - 1s 629us/step - loss: 0.2956 - accuracy: 0.8923


In [18]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy', test_acc)

313/313 [==============================] - 0s 540us/step - loss: 0.3652 - accuracy: 0.8652
Test accuracy 0.8651999831199646


In [20]:
predictions = model.predict(test_images)

In [21]:
predictions[0]

array([2.2768825e-06, 2.3815544e-07, 3.4903323e-06, 1.3308560e-05,
       1.4168981e-07, 1.2476746e-02, 1.1192313e-06, 1.3103317e-01,
       1.6403501e-05, 8.5645300e-01], dtype=float32)

In [22]:
np.argmax(predictions[0])

9

In [23]:
test_labels[0]

9

In [24]:
img = test_images[0]
print(img.shape)

(28, 28)


In [26]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [27]:
prediction_single = model.predict(img)
print(prediction_single)

[[2.2768829e-06 2.3815502e-07 3.4903298e-06 1.3308525e-05 1.4168984e-07
  1.2476731e-02 1.1192294e-06 1.3103305e-01 1.6403519e-05 8.5645318e-01]]


In [28]:
np.argmax(prediction_single[0])

9