<img src='tensor.png'>

<img src='parcs.png'>

In [8]:
pip install tensorflow

  Using cached tensorflow-2.4.1-cp38-cp38-win_amd64.whl (370.7 MB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Processing c:\users\felip\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501\termcolor-1.1.0-py3-none-any.whl
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Using cached protobuf-3.15.6-py2.py3-none-any.whl (173 kB)

  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Processing c:\users\felip\appdata\local\pip\cache\wheels\5f\fd\9e\b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73\wrapt-1.12.1-py3-none-any.whl
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
  Using cached absl_py-0.12.0-py3-none-any.whl (129 kB)
  Using cached grpcio-1.32

In [9]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
print('Succes')

Succes


In [10]:
fashion_mnist = keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [11]:
train_images.shape

(60000, 28, 28)

In [12]:
len(train_labels)

60000

In [13]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [14]:
test_images.shape

(10000, 28, 28)

In [15]:
len(test_labels)

10000

In [16]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [17]:
train_images = train_images / 255.0

test_images = test_images / 255.0

In [18]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [20]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 605us/step - loss: 0.6193 - accuracy: 0.7848
Epoch 2/5
1875/1875 [==============================] - 1s 651us/step - loss: 0.3865 - accuracy: 0.8625
Epoch 3/5
1875/1875 [==============================] - 1s 604us/step - loss: 0.3398 - accuracy: 0.8751
Epoch 4/5
1875/1875 [==============================] - 1s 594us/step - loss: 0.3128 - accuracy: 0.8847
Epoch 5/5
1875/1875 [==============================] - 1s 600us/step - loss: 0.2945 - accuracy: 0.8894


In [21]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 505us/step - loss: 0.3453 - accuracy: 0.8751
Test accuracy: 0.8751000165939331


In [22]:
predictions = model.predict(test_images)

In [23]:
predictions[0]

array([1.3440024e-05, 1.2660604e-07, 2.9545291e-07, 3.7175690e-07,
       4.4244521e-06, 1.6798639e-03, 1.0888663e-05, 6.8623058e-02,
       4.7816953e-05, 9.2961979e-01], dtype=float32)

In [24]:
np.argmax(predictions[0])

9

In [25]:
test_labels[0]

9

In [26]:
img = test_images[0]

print(img.shape)

(28, 28)


In [27]:
img = (np.expand_dims(img,0))

print(img.shape)

(1, 28, 28)


In [28]:
predictions_single = model.predict(img)

print(predictions_single)

[[1.3440038e-05 1.2660604e-07 2.9545237e-07 3.7175690e-07 4.4244521e-06
  1.6798630e-03 1.0888673e-05 6.8623058e-02 4.7816953e-05 9.2961979e-01]]


In [29]:
np.argmax(predictions_single[0])

9

### Oficina 5.2

In [32]:
#Preparação do modelo para treino com 50 neurônios
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(50, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                510       
Total params: 39,760
Trainable params: 39,760
Non-trainable params: 0
_________________________________________________________________


In [33]:
#Compilando o modelo
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [36]:
#Treinando o modelo com 4 iterações
model.fit(train_images, train_labels, epochs=4)

Epoch 1/4
1875/1875 [==============================] - 1s 603us/step - loss: 0.3143 - accuracy: 0.8848
Epoch 2/4
1875/1875 [==============================] - 1s 598us/step - loss: 0.3028 - accuracy: 0.8889
Epoch 3/4
1875/1875 [==============================] - 1s 595us/step - loss: 0.2936 - accuracy: 0.8921
Epoch 4/4
1875/1875 [==============================] - 1s 592us/step - loss: 0.2840 - accuracy: 0.8951


In [38]:
#Avaliação da acurácia do conjunto de dados de teste
test_loss, test_acc = model.evaluate(test_images, test_labels)

print('Test accuracy:', test_acc)

313/313 [==============================] - 0s 540us/step - loss: 0.3561 - accuracy: 0.8725
Test accuracy: 0.8725000023841858
